// Package middleware provides production-ready HTTP middleware for gofastapi.
// Each middleware is framework-agnostic: it operates on crud.Context and
// can therefore be used with any router that implements that interface.
//
// Available middleware:
//   - JWT()        — JSON Web Token authentication
//   - CORS()       — Cross-Origin Resource Sharing headers
//   - RateLimit()  — per-IP token-bucket rate limiter
//   - Logger()     — structured request/response logging (zap)
//   - Recovery()   — panic recovery with stack trace logging
//   - Cache()      — in-memory response cache
package middleware

import (
	"errors"
	"fmt"
	"net/http"
	"os"
	"strings"
	"time"

	jwtv5 "github.com/golang-jwt/jwt/v5"
)

// ─────────────────────────────────────────────────────────────────────────────
// Context — duplicated here to avoid an import cycle with crud/
// ─────────────────────────────────────────────────────────────────────────────

// Context is the minimal HTTP context interface required by middleware.
// It mirrors crud.Context exactly.
type Context interface {
	Request() *http.Request
	BindJSON(v any) error
	JSON(status int, v any)
	Param(name string) string
	Query(name string) string
	QueryDefault(name, defaultValue string) string
	Set(key string, value any)
	Get(key string) (any, bool)
	Abort()
	Next()
	ClientIP() string
}

// MiddlewareFunc is a middleware handler function.
type MiddlewareFunc func(ctx Context)

// ─────────────────────────────────────────────────────────────────────────────
// JWT Claims
// ─────────────────────────────────────────────────────────────────────────────

// JWTClaims is the standard payload stored inside a gofastapi JWT token.
// Applications can embed this struct to extend the claims.
type JWTClaims struct {
	// UserID is the primary key of the authenticated user.
	UserID uint `json:"user_id"`
	// UserEmail is the email of the authenticated user.
	UserEmail string `json:"user_email"`
	// Role is the user's access role (e.g. "admin", "member").
	Role string `json:"role"`
	jwtv5.RegisteredClaims
}

// ContextKeyUser is the context key under which JWTClaims is stored.
const ContextKeyUser = "gofastapi_user"

// ─────────────────────────────────────────────────────────────────────────────
// JWT configuration
// ─────────────────────────────────────────────────────────────────────────────

// JWTConfig configures the JWT middleware.
type JWTConfig struct {
	// Secret is the HMAC signing secret. Read from JWT_SECRET env by default.
	Secret string
	// TokenLookup controls where the token is expected.
	// Format: "header:Authorization" | "query:token" | "cookie:jwt"
	// Default: "header:Authorization"
	TokenLookup string
	// ContextKey is the key used to store JWTClaims in the request context.
	// Default: ContextKeyUser
	ContextKey string
	// AllowedRoles, if non-empty, requires the token's Role to be in this list.
	AllowedRoles []string
	// Expiry is the lifetime for tokens generated by GenerateToken.
	// Default: 24 hours.
	Expiry time.Duration
}

var defaultJWTConfig = JWTConfig{
	Secret:      envOrDefault("JWT_SECRET", "change-me-in-production"),
	TokenLookup: "header:Authorization",
	ContextKey:  ContextKeyUser,
	Expiry:      24 * time.Hour,
}

// ─────────────────────────────────────────────────────────────────────────────
// JWT middleware
// ─────────────────────────────────────────────────────────────────────────────

var (
	errMissingToken      = errors.New("authentication token is missing")
	errInvalidToken      = errors.New("authentication token is invalid or expired")
	errInvalidSignMethod = errors.New("unexpected JWT signing method")
	errInsufficientRole  = errors.New("your role does not have permission to access this resource")
)

// JWT returns a middleware that validates a Bearer JWT token on every request.
// The decoded claims are stored in the context under ContextKeyUser.
//
// Usage:
//
//	gofastapi.Use(middleware.JWT())
//	// or with config:
//	gofastapi.Use(middleware.JWT(middleware.JWTConfig{Secret: "my-secret"}))
func JWT(configs ...JWTConfig) MiddlewareFunc {
	cfg := defaultJWTConfig
	if len(configs) > 0 {
		cfg = configs[0]
		if cfg.Secret == "" {
			cfg.Secret = envOrDefault("JWT_SECRET", "change-me-in-production")
		}
		if cfg.TokenLookup == "" {
			cfg.TokenLookup = "header:Authorization"
		}
		if cfg.ContextKey == "" {
			cfg.ContextKey = ContextKeyUser
		}
		if cfg.Expiry == 0 {
			cfg.Expiry = 24 * time.Hour
		}
	}

	return func(ctx Context) {
		tokenStr := extractToken(ctx, cfg.TokenLookup)
		if tokenStr == "" {
			sendUnauthorized(ctx, errMissingToken)
			return
		}

		claims := &JWTClaims{}
		token, err := jwtv5.ParseWithClaims(
			tokenStr,
			claims,
			func(t *jwtv5.Token) (any, error) {
				if _, ok := t.Method.(*jwtv5.SigningMethodHMAC); !ok {
					return nil, fmt.Errorf("%w: %v", errInvalidSignMethod, t.Header["alg"])
				}
				return []byte(cfg.Secret), nil
			},
		)

		if err != nil || !token.Valid {
			sendUnauthorized(ctx, errInvalidToken)
			return
		}

		// Role-based access control.
		if len(cfg.AllowedRoles) > 0 {
			allowed := false
			for _, r := range cfg.AllowedRoles {
				if r == claims.Role {
					allowed = true
					break
				}
			}
			if !allowed {
				sendForbidden(ctx, errInsufficientRole)
				return
			}
		}

		ctx.Set(cfg.ContextKey, claims)
		ctx.Next()
	}
}

// JWTOptional is like JWT but does not abort when no token is present.
// If a valid token is found it is stored in context; otherwise the request
// proceeds with no claims set.
func JWTOptional(configs ...JWTConfig) MiddlewareFunc {
	cfg := defaultJWTConfig
	if len(configs) > 0 {
		cfg = configs[0]
	}
	return func(ctx Context) {
		tokenStr := extractToken(ctx, cfg.TokenLookup)
		if tokenStr != "" {
			claims := &JWTClaims{}
			token, err := jwtv5.ParseWithClaims(tokenStr, claims,
				func(t *jwtv5.Token) (any, error) {
					if _, ok := t.Method.(*jwtv5.SigningMethodHMAC); !ok {
						return nil, errInvalidSignMethod
					}
					return []byte(cfg.Secret), nil
				},
			)
			if err == nil && token.Valid {
				ctx.Set(cfg.ContextKey, claims)
			}
		}
		ctx.Next()
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// Token generation helpers
// ─────────────────────────────────────────────────────────────────────────────

// GenerateToken creates a signed HS256 JWT token for the given user.
//
//	token, err := middleware.GenerateToken(1, "alice@example.com", "admin", "my-secret", 24*time.Hour)
func GenerateToken(userID uint, email, role, secret string, expiry time.Duration) (string, error) {
	claims := JWTClaims{
		UserID:    userID,
		UserEmail: email,
		Role:      role,
		RegisteredClaims: jwtv5.RegisteredClaims{
			ExpiresAt: jwtv5.NewNumericDate(time.Now().Add(expiry)),
			IssuedAt:  jwtv5.NewNumericDate(time.Now()),
		},
	}
	token := jwtv5.NewWithClaims(jwtv5.SigningMethodHS256, claims)
	return token.SignedString([]byte(secret))
}

// GetClaims retrieves the JWTClaims stored by JWT middleware from the context.
// Returns nil if no claims are present (i.e. unauthenticated request).
func GetClaims(ctx Context) *JWTClaims {
	v, ok := ctx.Get(ContextKeyUser)
	if !ok {
		return nil
	}
	claims, _ := v.(*JWTClaims)
	return claims
}

// RequireUserID is a convenience helper that returns the authenticated user's
// ID from the context, or 0 if not authenticated.
func RequireUserID(ctx Context) uint {
	if c := GetClaims(ctx); c != nil {
		return c.UserID
	}
	return 0
}

// ─────────────────────────────────────────────────────────────────────────────
// Internal helpers
// ─────────────────────────────────────────────────────────────────────────────

// extractToken parses the JWT token string from the request per the lookup rule.
func extractToken(ctx Context, lookup string) string {
	parts := strings.SplitN(lookup, ":", 2)
	if len(parts) != 2 {
		return ""
	}
	source, name := parts[0], parts[1]
	switch source {
	case "header":
		val := ctx.Request().Header.Get(name)
		if strings.HasPrefix(val, "Bearer ") {
			return strings.TrimPrefix(val, "Bearer ")
		}
		return val
	case "query":
		return ctx.Query(name)
	case "cookie":
		cookie, err := ctx.Request().Cookie(name)
		if err == nil {
			return cookie.Value
		}
	}
	return ""
}

func sendUnauthorized(ctx Context, err error) {
	ctx.JSON(http.StatusUnauthorized, map[string]any{
		"success": false,
		"error": map[string]string{
			"code":    "UNAUTHORIZED",
			"message": err.Error(),
		},
	})
	ctx.Abort()
}

func sendForbidden(ctx Context, err error) {
	ctx.JSON(http.StatusForbidden, map[string]any{
		"success": false,
		"error": map[string]string{
			"code":    "FORBIDDEN",
			"message": err.Error(),
		},
	})
	ctx.Abort()
}

func envOrDefault(key, def string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return def
}
